lti_tool_provider_attributes.settings:
  type: config_object
  label: LTI tool provider attributes settings
  mapping:
    mapped_attributes:
      type: mapping
      label: Configure mapped attributes
      mapping:
        user_attribute:
          type: string
          label: User Attribute
        lti_attribute:
          type: string
          label: LTI Attribute
