lti_tool_provider.settings:
  type: config_object
  label: 'LTI tool provider settings'
  mapping:
    iframe:
      type: boolean
      label: 'Allow LTI content to be displayed in an iframe.'
    destination:
      type: string
      label: 'Destination to redirect to after launch and successful authentication.'
    v1p0_lti_launch:
      type: sequence
      label: List of LTI launch data for v1p0
      sequence:
        type: string
        label: Name
    v1p0_lti_roles:
      type: sequence
      label: List of LTI roles for v1p0
      sequence:
        type: string
        label: Name
    v1p3_lti_launch:
      type: sequence
      label: List of LTI launch data for v1p3
      sequence:
        type: string
        label: Name
    v1p3_lti_roles:
      type: sequence
      label: List of LTI roles for v1p3
      sequence:
        type: string
        label: Name
