lti_tool_provider.settings:
  type: config_object
  label: 'LTI tool provider settings'
  mapping:
    iframe:
      type: boolean
      label: 'Allow LTI content to be displayed in an iframe.'
    destination:
      type: string
      label: 'Destination to redirect to after launch and successful authentication.'
    lti_launch:
      type: sequence
      label: List of LTI launch data
      sequence:
        type: string
        label: Name
    lti_roles:
      type: sequence
      label: List of LTI roles
      sequence:
        type: string
        label: Name
