lti_tool_provider_content.settings:
  type: config_object
  label: LTI tool provider content settings
  mapping:
    enabled:
      type: boolean
      label: Enabled
    entity_types:
      type: mapping
      label: Entity Types
      mapping:
        key:
          type: string
          label: Key
        value:
          type: string
          label: Value
    entity_bundles:
      type: mapping
      label: Entity Bundles
      mapping:
        key:
          type: string
          label: Key
        value:
          type: string
          label: Value
    entity_defaults:
      type: mapping
      label: Entity Bundles
      mapping:
        key:
          type: string
          label: Key
        value:
          type: mapping
          label: Bundle Fields
          mapping:
            key:
              type: string
              label: Key
            value:
              type: string
              label: Value
    owner:
      type: boolean
      label: Filter by Owner
    sync:
      type: boolean
      label: Sync Entity Fields
