condition.plugin.http_client_error_status:
  type: condition.plugin
  mapping:
    request_401:
      type: boolean
      label: 'Request 401'
    request_403:
      type: boolean
      label: 'Request 403'
    request_404:
      type: boolean
      label: 'Request 403'
