<?php

/**
 * @file
 * Defines an iframe field with all attributes.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\iframe\Hook\IframeHooks;
use Drupal\Core\Routing\RouteMatchInterface;

if (!defined('IFRAME_DEBUG_LEVEL')) {
  define('IFRAME_DEBUG_LEVEL', 0);
}

/**
 * Debug the iframe module.
 *
 * Function "dpr" is from devel-module, we will use it if exists.
 */
function iframe_debug($level, $func = 'iframe', $debugvar = NULL): void {
  if ($level <= IFRAME_DEBUG_LEVEL) {
    try {
      $develdumper = \Drupal::service('devel.dumper');
    }
    catch (Exception) {
      $develdumper = '';
    }
    if (isset($develdumper) && is_object($develdumper)) {
      $develdumper->dumpOrExport($debugvar, $func, NULL, 'drupal_variable');
    }
    else {
      if (is_object($debugvar)) {
        $debugvar = [get_class($debugvar), get_class_methods($debugvar)];
      }
      error_log('ID: ' . $level . ' ' . $func);
      \Drupal::messenger()->addMessage('[iframe(' . $level . ')] ' . $func . ' ' . print_r($debugvar, TRUE), 'warning');
    }
  }
}

/**
 * Implements hook_help().
 */
#[LegacyHook]
function iframe_help($route_name, RouteMatchInterface $route_match) {
  return \Drupal::service(IframeHooks::class)->help($route_name, $route_match);
}

/**
 * Implements hook_theme().
 */
#[LegacyHook]
function iframe_theme(): array {
  return \Drupal::service(IframeHooks::class)->theme();
}
